"""field name changed

Revision ID: 144ce5333440
Revises: d4fce6104f96
Create Date: 2025-05-19 22:48:32.918266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '144ce5333440'
down_revision: Union[str, None] = 'd4fce6104f96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mapper', sa.Column('hash_str', sa.String(length=255), nullable=False))
    op.drop_column('url_mapper', 'hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('url_mapper', sa.Column('hash', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('url_mapper', 'hash_str')
    # ### end Alembic commands ###
